# =============================================================================
# Istiod Helm Values
# =============================================================================

meshConfig:
  enableAutoMtls: true
  accessLogFile: /dev/stdout

global:
  proxy:
    holdApplicationUntilProxyStarts: true
